org.gradle.jvmargs=-Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Optimizaciones de compilación incremental
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
org.gradle.daemon=false
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.resvalues=false
